remote_theme: rundocs/jekyll-rtd-theme
title: Aries Interoperability Test Results
description: A summary of the Hyperledger Aries Interoperability Profile (AIP) Test Harness runs

scss: |
  div.markdown-body div.tip div.title {height: 0;padding-top: 0.5rem !important;overflow: hidden;}